COPY INTO "DBT_TGT"."TGT"."CUSTOMERS"
FROM (
    SELECT $1, $2, $3, $4, $5
    FROM '@"DBT_TGT"."TGT"."MY_INTERNAL_STAGE"'
)
FILES = ('MOCK_DATA _TEST.csv')
FILE_FORMAT = (
    TYPE=CSV,
    SKIP_HEADER=1,
    FIELD_DELIMITER=',',
    TRIM_SPACE=TRUE,
    FIELD_OPTIONALLY_ENCLOSED_BY='"',
    REPLACE_INVALID_CHARACTERS=TRUE,
    DATE_FORMAT='DD-MM-YYYY',
    TIME_FORMAT=AUTO,
    TIMESTAMP_FORMAT=AUTO
)
ON_ERROR=ABORT_STATEMENT;
